service: import-service-5-new
frameworkVersion: '2'
variablesResolutionMode: 20210219


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::import-service-5'
    - Effect: "Allow"
      Action: 
         - 's3:PutObject'
      Resource: "arn:aws:s3:::import-service-5/*" 
    - Effect: "Allow"
      Action:
       - "s3:*"
      Resource: "arn:aws:s3:::import-service-5/*"

plugins:
   ["serverless-webpack", "serverless-offline"]

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true


functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          method: get
          path: import
          querystrings:
            name: true
          cors:
            origin: "*"
        
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: 'import-service-5'
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv

      