service: lesson4-2
app: lesson4-2


frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x


# you can define service wide environment variables here
  environment:
    PG_HOST: lesson4.cptghxjj2tzc.us-east-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: lesson4
    PG_USERNAME: postgres
    PG_PASSWORD: qwerty1234

functions:
  createPGDb:
    handler: pg-client-lambda.invoke

